### ISSUE TITLE
There's nothing here

### ISSUE THREAD

**Issue by MaxwellGBrown** [clagraff/build-an-api-app#1]
There's nothing here.

**Comment by clagraff** [comment]
im getting there

**Comment by MaxwellGBrown** [comment]
no I said here not there

**Comment by clagraff** [comment]
![](https://media2.giphy.com/media/IIlfLqGBAyxLa/giphy.gif?cid=3640f6095c9bad2c6d634c51325fbfb1)

**Comment by MaxwellGBrown** [comment]
![](https://media.giphy.com/media/xdFUTuc9aqvbG/giphy.gif)

**Comment by clagraff** [comment]
![](https://media.giphy.com/media/62cXfuNSbdDQb7YuG3/giphy.gif)

**Comment by MaxwellGBrown** [comment]
There's still basically nothing here; I'm going to keep this issue open until there's substance.

**Comment by clagraff** [comment]
well, I made another commit. so thats something. 
i didnt realize how long it takes to write stuff.

https://buildanapi.dev/  is _slowly_ coming together

**Comment by MaxwellGBrown** [comment]
With the addition of web serving I think we can safely say that there is "something" here.

Perhaps include that link in a README.md 😉
